# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import vectordb_pb2 as vectordb__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vectordb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorDBStub(object):
    """VectorDB exposes CRUD plus similarity search over named collections of
    vectors. PutVector auto-creates a collection (inferring its dimension from
    the first vector) when one does not already exist.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutVector = channel.unary_unary(
                '/polign.v1.VectorDB/PutVector',
                request_serializer=vectordb__pb2.PutVectorRequest.SerializeToString,
                response_deserializer=vectordb__pb2.PutVectorResponse.FromString,
                _registered_method=True)
        self.PutVectors = channel.unary_unary(
                '/polign.v1.VectorDB/PutVectors',
                request_serializer=vectordb__pb2.PutVectorsRequest.SerializeToString,
                response_deserializer=vectordb__pb2.PutVectorsResponse.FromString,
                _registered_method=True)
        self.GetVector = channel.unary_unary(
                '/polign.v1.VectorDB/GetVector',
                request_serializer=vectordb__pb2.GetVectorRequest.SerializeToString,
                response_deserializer=vectordb__pb2.GetVectorResponse.FromString,
                _registered_method=True)
        self.GetVectors = channel.unary_unary(
                '/polign.v1.VectorDB/GetVectors',
                request_serializer=vectordb__pb2.GetVectorsRequest.SerializeToString,
                response_deserializer=vectordb__pb2.GetVectorsResponse.FromString,
                _registered_method=True)
        self.ListVectors = channel.unary_unary(
                '/polign.v1.VectorDB/ListVectors',
                request_serializer=vectordb__pb2.ListVectorsRequest.SerializeToString,
                response_deserializer=vectordb__pb2.ListVectorsResponse.FromString,
                _registered_method=True)
        self.DeleteVector = channel.unary_unary(
                '/polign.v1.VectorDB/DeleteVector',
                request_serializer=vectordb__pb2.DeleteVectorRequest.SerializeToString,
                response_deserializer=vectordb__pb2.DeleteVectorResponse.FromString,
                _registered_method=True)
        self.DeleteVectors = channel.unary_unary(
                '/polign.v1.VectorDB/DeleteVectors',
                request_serializer=vectordb__pb2.DeleteVectorsRequest.SerializeToString,
                response_deserializer=vectordb__pb2.DeleteVectorsResponse.FromString,
                _registered_method=True)
        self.UpdateMetadata = channel.unary_unary(
                '/polign.v1.VectorDB/UpdateMetadata',
                request_serializer=vectordb__pb2.UpdateMetadataRequest.SerializeToString,
                response_deserializer=vectordb__pb2.UpdateMetadataResponse.FromString,
                _registered_method=True)
        self.SearchVectors = channel.unary_unary(
                '/polign.v1.VectorDB/SearchVectors',
                request_serializer=vectordb__pb2.SearchVectorsRequest.SerializeToString,
                response_deserializer=vectordb__pb2.SearchVectorsResponse.FromString,
                _registered_method=True)
        self.DescribeCollection = channel.unary_unary(
                '/polign.v1.VectorDB/DescribeCollection',
                request_serializer=vectordb__pb2.DescribeCollectionRequest.SerializeToString,
                response_deserializer=vectordb__pb2.DescribeCollectionResponse.FromString,
                _registered_method=True)
        self.CreateCollection = channel.unary_unary(
                '/polign.v1.VectorDB/CreateCollection',
                request_serializer=vectordb__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=vectordb__pb2.CreateCollectionResponse.FromString,
                _registered_method=True)
        self.GetCollection = channel.unary_unary(
                '/polign.v1.VectorDB/GetCollection',
                request_serializer=vectordb__pb2.GetCollectionRequest.SerializeToString,
                response_deserializer=vectordb__pb2.GetCollectionResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/polign.v1.VectorDB/ListCollections',
                request_serializer=vectordb__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=vectordb__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)
        self.DeleteCollection = channel.unary_unary(
                '/polign.v1.VectorDB/DeleteCollection',
                request_serializer=vectordb__pb2.DeleteCollectionRequest.SerializeToString,
                response_deserializer=vectordb__pb2.DeleteCollectionResponse.FromString,
                _registered_method=True)
        self.VerifyCollection = channel.unary_unary(
                '/polign.v1.VectorDB/VerifyCollection',
                request_serializer=vectordb__pb2.VerifyCollectionRequest.SerializeToString,
                response_deserializer=vectordb__pb2.VerifyCollectionResponse.FromString,
                _registered_method=True)


class VectorDBServicer(object):
    """VectorDB exposes CRUD plus similarity search over named collections of
    vectors. PutVector auto-creates a collection (inferring its dimension from
    the first vector) when one does not already exist.
    """

    def PutVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutVectors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVectors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVectors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVectors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchVectors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCollection(self, request, context):
        """Collection admin: the explicit lifecycle for collections on
        customer-owned backends (bring-your-own bucket). Available only when the
        server runs the collections registry (-byo-store); otherwise these
        return Unimplemented. Collections on the server's default store need
        none of this and keep auto-creating on first write.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutVector': grpc.unary_unary_rpc_method_handler(
                    servicer.PutVector,
                    request_deserializer=vectordb__pb2.PutVectorRequest.FromString,
                    response_serializer=vectordb__pb2.PutVectorResponse.SerializeToString,
            ),
            'PutVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.PutVectors,
                    request_deserializer=vectordb__pb2.PutVectorsRequest.FromString,
                    response_serializer=vectordb__pb2.PutVectorsResponse.SerializeToString,
            ),
            'GetVector': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVector,
                    request_deserializer=vectordb__pb2.GetVectorRequest.FromString,
                    response_serializer=vectordb__pb2.GetVectorResponse.SerializeToString,
            ),
            'GetVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVectors,
                    request_deserializer=vectordb__pb2.GetVectorsRequest.FromString,
                    response_serializer=vectordb__pb2.GetVectorsResponse.SerializeToString,
            ),
            'ListVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVectors,
                    request_deserializer=vectordb__pb2.ListVectorsRequest.FromString,
                    response_serializer=vectordb__pb2.ListVectorsResponse.SerializeToString,
            ),
            'DeleteVector': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVector,
                    request_deserializer=vectordb__pb2.DeleteVectorRequest.FromString,
                    response_serializer=vectordb__pb2.DeleteVectorResponse.SerializeToString,
            ),
            'DeleteVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVectors,
                    request_deserializer=vectordb__pb2.DeleteVectorsRequest.FromString,
                    response_serializer=vectordb__pb2.DeleteVectorsResponse.SerializeToString,
            ),
            'UpdateMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMetadata,
                    request_deserializer=vectordb__pb2.UpdateMetadataRequest.FromString,
                    response_serializer=vectordb__pb2.UpdateMetadataResponse.SerializeToString,
            ),
            'SearchVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchVectors,
                    request_deserializer=vectordb__pb2.SearchVectorsRequest.FromString,
                    response_serializer=vectordb__pb2.SearchVectorsResponse.SerializeToString,
            ),
            'DescribeCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeCollection,
                    request_deserializer=vectordb__pb2.DescribeCollectionRequest.FromString,
                    response_serializer=vectordb__pb2.DescribeCollectionResponse.SerializeToString,
            ),
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=vectordb__pb2.CreateCollectionRequest.FromString,
                    response_serializer=vectordb__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'GetCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollection,
                    request_deserializer=vectordb__pb2.GetCollectionRequest.FromString,
                    response_serializer=vectordb__pb2.GetCollectionResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=vectordb__pb2.ListCollectionsRequest.FromString,
                    response_serializer=vectordb__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'DeleteCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCollection,
                    request_deserializer=vectordb__pb2.DeleteCollectionRequest.FromString,
                    response_serializer=vectordb__pb2.DeleteCollectionResponse.SerializeToString,
            ),
            'VerifyCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyCollection,
                    request_deserializer=vectordb__pb2.VerifyCollectionRequest.FromString,
                    response_serializer=vectordb__pb2.VerifyCollectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'polign.v1.VectorDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('polign.v1.VectorDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorDB(object):
    """VectorDB exposes CRUD plus similarity search over named collections of
    vectors. PutVector auto-creates a collection (inferring its dimension from
    the first vector) when one does not already exist.
    """

    @staticmethod
    def PutVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polign.v1.VectorDB/PutVector',
            vectordb__pb2.PutVectorRequest.SerializeToString,
            vectordb__pb2.PutVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polign.v1.VectorDB/PutVectors',
            vectordb__pb2.PutVectorsRequest.SerializeToString,
            vectordb__pb2.PutVectorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polign.v1.VectorDB/GetVector',
            vectordb__pb2.GetVectorRequest.SerializeToString,
            vectordb__pb2.GetVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polign.v1.VectorDB/GetVectors',
            vectordb__pb2.GetVectorsRequest.SerializeToString,
            vectordb__pb2.GetVectorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polign.v1.VectorDB/ListVectors',
            vectordb__pb2.ListVectorsRequest.SerializeToString,
            vectordb__pb2.ListVectorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polign.v1.VectorDB/DeleteVector',
            vectordb__pb2.DeleteVectorRequest.SerializeToString,
            vectordb__pb2.DeleteVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polign.v1.VectorDB/DeleteVectors',
            vectordb__pb2.DeleteVectorsRequest.SerializeToString,
            vectordb__pb2.DeleteVectorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polign.v1.VectorDB/UpdateMetadata',
            vectordb__pb2.UpdateMetadataRequest.SerializeToString,
            vectordb__pb2.UpdateMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polign.v1.VectorDB/SearchVectors',
            vectordb__pb2.SearchVectorsRequest.SerializeToString,
            vectordb__pb2.SearchVectorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polign.v1.VectorDB/DescribeCollection',
            vectordb__pb2.DescribeCollectionRequest.SerializeToString,
            vectordb__pb2.DescribeCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polign.v1.VectorDB/CreateCollection',
            vectordb__pb2.CreateCollectionRequest.SerializeToString,
            vectordb__pb2.CreateCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polign.v1.VectorDB/GetCollection',
            vectordb__pb2.GetCollectionRequest.SerializeToString,
            vectordb__pb2.GetCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polign.v1.VectorDB/ListCollections',
            vectordb__pb2.ListCollectionsRequest.SerializeToString,
            vectordb__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polign.v1.VectorDB/DeleteCollection',
            vectordb__pb2.DeleteCollectionRequest.SerializeToString,
            vectordb__pb2.DeleteCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polign.v1.VectorDB/VerifyCollection',
            vectordb__pb2.VerifyCollectionRequest.SerializeToString,
            vectordb__pb2.VerifyCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
